services:

  mysql:
    image: mysql:8.0.34
    restart: always

    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=db

    ports:
      - "3306:3306"

